import type { Metadata } from 'next'
import { Barlow, Geist, Geist_Mono, Macondo } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const macondo = Macondo({
  variable: '--font-geist-macondo',
  subsets: ['latin'],
  weight: ['400'],
})

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${macondo.variable}   ${barlow.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
